language: python
python:
- '2.7'
env:
  global:
  - DJANGO_SETTINGS_MODULE=settings.ci
  - PYTHONPATH=project
  - DATABASE_URL=postgres://postgres:postgres@localhost/captable
  - SECRET_KEY=testingsonotsosecret
  - secure: N6TSuv+GSEcAYRRMzWErHKyZdI3K7BldfkGYC9/RViyJ/HS0OR/lOcw9kN3MJ3bsCDuuR6LVZl2xjzeBynOOBJHnrUBMXNcrJN8A/q8Pj7cxVMqfP4SKGeo4w9299ucIgH70LJJFrhZ26e5zkHkilnblOHm1sZAsCnM2U8CLJzw= # coveralls
install:
- pip install -r requirements/ci.txt
before_script:
- psql -c 'create database captable;' -U postgres
- django-admin.py syncdb --noinput
- django-admin.py migrate --noinput
script:
- nosetests --with-coverage --cover-package=apps.captable
after_script:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: XjqYdvlHsGjXpHUPEc2k6dYXoluPVuqIh8Xmyne9m5GPuVI1JS3yIWUKpB/6LtAPkOjRWDS/BCKq+qVUZyqU7fixR2bgYC9ez9Hbhyvl/5UYglzpWqC7By/53mg2wluo3eMwrUdTe+tC3rVkE2bys+zRRn+2E4k7s2NZLrndLdU=
  app: captable
  on:
    repo: dbinetti/captable
